### ISSUE TITLE
Uris being downloaded again and again?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [sjdirect/abot#125] opened 2016-04-07 01:33 UTC
Hello,

I'm using a HyperLinkParser like this:

    public class MyHyperLinkParser : IHyperLinkParser
    {
        public Uri Base { get; set; }
        public HtmlParser HtmlParser { get; set; } = new HtmlParser();
        public IEnumerable<Uri> GetLinks(CrawledPage crawledPage)
        {
            var doc = HtmlParser.Parse(crawledPage.Content.Text);

            return doc.QuerySelectorAll(".main-nav a[href]").Select(a => a.Attributes["href"].Value).Select(href => {
                var uri = new Uri(Base, href);
                Console.WriteLine(uri);
                return uri;
            });
        }
    }

It seems that the pages that are downloaded are also passed through this method (of course), but then the same links are found again and again, as this is the top menu. But they are not supposed to be crawled more than once...!

What's the standard way of doing this?

**Comment by sjdirect** [comment] 2016-04-07 06:17
The HyperLinkParser's job is to get all the hyperlinks on the page. It doesn't know or care if that link has already been crawled. That decision is made in higher up the stack. Specifically the ShouldCrawlPage method on line 787 of [WebCrawler.cs](https://github.com/sjdirect/abot/blob/master/Abot/Crawler/WebCrawler.cs). 

Closing this issue as it is by design.

**Closed by sjdirect** 2016-04-07 06:17 UTC
