### ISSUE TITLE
Abot Suddenly stooped giving crawl results for certain sites inside Azure Worker

### ISSUE THREAD

**Issue by obender** [sjdirect/abot#130] opened 2016-06-06 05:02 UTC
Hi, 
We have been using abot for few years now, and recently it just stoped working on our azure environments  for part of the sites. 

It just give 1 page as a result, 
and no error returns , ErrorOccurred equals false!
_result = crawler.Crawl(_url);
_result.ErrorOccurred=false

All dll's are the same version on azure as on local... all setings are the same, there is no firewall block cause other crawler crawl successfully same site...

Please help I am out of options...

**Comment by sjdirect** [comment] 2016-06-06 05:14
You will need to look at your abotlog.txt file. If that doesn't give you anything then change logging level from INFO to DEBUG. Also it is possible Azure is rate limiting or blocking your calls out. I would also reach out to them if the logs give you no errors or other clues. Especially if that same configuration works locally.

Closing this issue since it doesn't contain any data that would even allow me to make a guess at what might be the issue. Feel free to open another one if you have narrowed down the cause.

**Closed by sjdirect** 2016-06-06 05:14 UTC

**Comment by obender** [comment] 2016-06-06 14:55
Where is that log located ?

**Comment by obender** [comment] 2016-06-06 14:56
It's not a network Issue cause other crawler that I had wrote have full accesses and it's working after abot

**Comment by sjdirect** [comment] 2016-06-06 15:28
Its located in the bin directory of the final build. Usually under bin/debug/abotlog.txt on your local machine. Not sure how you would get to it on azure unless you have rdp access.
