### ISSUE TITLE
Keywords and output 

### ISSUE THREAD

**Issue by gsogol** [sjdirect/abot#70] opened 2015-04-24 16:54 UTC
1) how do you specify keywords to search for in say Google  
2) how do you search for an email address or say contact form? Any strategies?
3) can just run this in azure via say webjobs and how do I output results to something like azure table storage?
4) great job

**Comment by Ruffio** [comment] 2015-04-29 07:39
@gsogol what you are writting is not an issue/bug. Please use the forum for asking questions at: https://groups.google.com/forum/#!forum/abot-web-crawler

This can be closed as not a bug.

**Comment by sjdirect** [comment] 2015-04-29 23:44
Thanks Ruffio, closing this...

**Closed by sjdirect** 2015-04-29 23:44 UTC
