### ISSUE TITLE
Incorrect usage of ThreadManager means it does nothing

### ISSUE THREAD

**Issue by YairHalberstadt** [sjdirect/abot#225] opened 2020-12-21 15:15 UTC
The ThreadManager tis designed to make sure that only a limited number of actions run at once. It's `DoWork` method takes an `Action`.

At the callsite a lambda is passed in like this: ` _threadManager.DoWork(async () => await ProcessPage(_scheduler.GetNext()));`

The lambda is converted to an `async void` method, and so this is effectively identical to:

 `_threadManager.DoWork(() => ProcessPage(_scheduler.GetNext()));`
 
 The `Task` returned by `ProcessPage` is thus dropped.
 
 What this means in practice is the `Action` passed to the `ThreadManager` returns as soon as the `ProcessPage` calls `_httpClient.SendAsync`, before the web request completes asynchronously and the page is actually crawled. This means the action will return extremely quickly, as most of the time is spent waiting for the http call to complete.
 
 The `ThreadManager` thus only serves to make sure that a limited number of requests are in this short section of time between kicking them off and starting the http request. Similarly all it's logic for cancelling requests, handling exceptions and checking which requests are running only affect this short section of time.
 
 My recommendation is that you have no need for a `ThreadManager`. Now that you are non-blocking (by using async await for your web requests) the `TaskScheduler` is perfectly capable of making sure the correct number of threads are used. You also don't need to use `Task.Run` anywhere: Since the time between starting to crawl a page and the call to `_httpClient.SendAsync` is very small there is no point parallelizing it.

**Comment by YairHalberstadt** [comment] 2020-12-21 15:20
I've opened a draft PR at https://github.com/sjdirect/abot/pull/226 to show the general direction I would go in to fix this. I don't have time to do much more at the moment I'm afraid :-(

Anyway good luck!

**Comment by sjdirect** [comment] 2021-01-25 17:00
Unfortunately I don't either. The problem is that interface has been around since the initial implementation of using threads directly. We decided to keep the abstraction to avoid a major breaking change.

**Comment by sjdirect** [comment] 2021-02-13 17:42
Can you demonstrate a unit test that proves it does nothing? The current implementation holds the maxconcurrenthttprequests to the configured amount and also provides the concurrency of processing of those completed requests.

**Comment by sjdirect** [comment] 2021-02-23 19:24
Closing until a test can be submitted in regards to my last comment.

**Closed** 2021-02-23 19:24 UTC
