### ISSUE TITLE
Cannot access Async events in newest version

### ISSUE THREAD

**Issue by JulioPablo** [sjdirect/abot#207] opened 2019-12-09 16:53 UTC
![image](https://user-images.githubusercontent.com/33587721/70455508-0de61d80-1a72-11ea-833f-62e4663f6ef8.png)

**Comment by sjdirect** [comment] 2019-12-09 18:14
Async events are gone after version 2.0. The syncronous events should be
used instead. Too many issues with users getting into trouble with the
async versions. Specifically the most common problem is that the async
processors (users code) would fall so far behind the crawl of large sites
that they were encountering memory issues.

**Comment by sjdirect** [comment] 2019-12-09 18:15
Closing since the removal was by design

**Closed** 2019-12-09 18:14 UTC

**Comment by JulioPablo** [comment] 2019-12-09 19:25
Gotcha, the documentation in the case, the documentation is outdated, the examples show usage of these.
