### ISSUE TITLE
All urls found were rejected by robots.txt file.

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#96] opened 2015-11-02 17:57 UTC
Can't crawl this site: http://www.provectio.fr
Seems that all urls found were rejected by robots.txt file. For example, this URL is rejected: http://www.provectio.fr/provectio-informatique/ 
I use this userAgentString : "Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko"
In Google Search Console, I found no errors for the robots.txt file & Urls.

**Comment by sjdirect** [comment] 2015-11-02 18:06
Hi,

See the workaround here... <https://github.com/sjdirect/nrobots/issues/3>

**Comment by LeMoussel** [comment] 2015-11-02 18:40
I set 
`IsIgnoreRobotsDotTextIfRootDisallowedEnabled="true"`
`isRespectRobotsDotTextEnabled="true"`

But I got for all Urls, debug message like this : *Page [http://www.provectio.fr/provectio-informatique/] not crawled, [Disallowed by robots.txt file], set IsRespectRobotsDotText=false in config file if you would like to ignore robots.txt files.*

No issue to crawl site with robots.txt consigne ?

**Comment by sjdirect** [comment] 2015-11-03 19:01
I'll take a closer look at this soon

**Comment by sjdirect** [comment] 2015-11-03 19:15
I believe the issue is that NRobots (the robots.txt lib that abot uses) is

turning...

Disallow: /*?

into...

Disallow: /*

which i believe allows the root but not anything else off of root. If
it treated it like this...

Disallow: /

then the workaround would work.


It is allowing the homepage but not any other pages which circumvents
the workaround above. Not sure Abot can handle this situation on its
own. A fix to NRobots might have to be done

**Comment by LeMoussel** [comment] 2015-11-04 05:59
I tested this library [RobotsTxt](https://bitbucket.org/cagdas/robotstxt), It's OK with it.
````C#
string UrlSite = "http://www.provectio.fr";
UriBuilder uriBuilder = new UriBuilder(UrlSite) { Path = "/robots.txt" };
string contentsOfRobotsTxtFile = new System.Net.WebClient().DownloadString(uriBuilder.Uri);
RobotsTxt.Robots robots = RobotsTxt.Robots.Load(contentsOfRobotsTxtFile);
bool canIGoThere = robots.IsPathAllowed("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0", new Uri("http://www.provectio.fr/provectio-informatique/").PathAndQuery);
````
To consider replacing NRobots by RobotsTxt library.

**Comment by sjdirect** [comment] 2015-11-04 06:44
Seems like the same library just a different version. Not sure I want to change it out in case that lib has other errors that mine doesn't. I think i have a workaround from Abot's side. Coming soon...

**Comment by sjdirect** [comment] 2015-11-04 06:50
Fixed in this commit https://github.com/sjdirect/abot/commit/4524db095b8b76c138599e4deaa10264b92416f6

**Closed** 2015-11-04 06:50 UTC

**Comment by LeMoussel** [comment] 2015-11-04 08:45
@ sjdirect Thank you for your support.
